import { StyleSheet } from 'react-native';
import Colors from '../constants/colors';

export default StyleSheet.create({
  safeContainer: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 120,
    backgroundColor: Colors.blacktransparent9,
  },
  container: {
    flex: 1,
    backgroundColor: Colors.black,
  },
  imageContainer: {
    position: 'relative',
    width: '100%',
    height: '100%',
  },
  backgroundVideo: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: -1,
  },
  backgroundImage: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: '100%',
    height: undefined,
    aspectRatio: 16 / 9,
    zIndex: -1,
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.blacktransparent7,
    paddingBottom: 50,
  },
  TitleText: {
    fontSize: 65,
    fontWeight: 'bold',
    color: Colors.white,
    marginBottom: 20,
    textAlign: 'center',
    fontFamily: 'Capsmall',
  },
  countdownContainer: {
    marginVertical: 20,
    alignItems: 'center',
    fontFamily: 'Capsmall_clean',
  },
  countdownRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '80%',
    fontFamily: 'Capsmall_clean',
  },
  countdownItem: {
    alignItems: 'center',
    fontFamily: 'Capsmall_clean',
  },
  countdownNumber: {
    fontSize: 37,
    fontWeight: 'bold',
    color: Colors.white,
    fontFamily: 'People',
  },
  countdownLabel: {
    fontSize: 17,
    fontWeight: 'normal',
    fontFamily: 'People',
    color: Colors.white,
  },
  button: {
    backgroundColor: Colors.greeninspi,
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 25,
    elevation: 3,
  },
  buttonText: {
    color: Colors.white,
    fontSize: 18,
    fontWeight: 'bold',
  },
  addressText: {
    fontSize: 12,
    fontStyle: 'italic',
    color: Colors.white,
    marginBottom: 10,
    textAlign: 'center',
  },
  buttonMaps: {
    marginTop: 10,
    padding: 10,
    backgroundColor: Colors.greeninspi,
    borderRadius: 5,
    alignItems: 'center',
  },
  buttonTextMaps: {
    color: Colors.white,
    fontWeight: 'bold',
  },
  expiredText: {
    fontSize: 22,
    color: Colors.white,
    marginVertical: 10,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  stepContainer: {
    gap: 8,
    marginBottom: 8,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  planImage: {
    width: '170%',
    height: 200,
    alignSelf: 'center',
    marginTop: 10,
  },
  subtitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: Colors.greeninspi,
    textAlign: 'center',
    textTransform: 'uppercase',
    marginBottom: 10,
    textShadowColor: Colors.blacktransparent3,
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
    fontFamily: 'Arial',
  },
  titleContainer: {
    marginBottom: 20,
  },
  socialMediaContainer: {
    marginTop: 20,
    marginBottom: 40,
    alignItems: 'center',
    padding: 10,
    backgroundColor: Colors.blacktransparent9,
    borderRadius: 10,
  },
  socialMediaTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.white,
    marginBottom: 10,
  },
  socialMediaIcons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '60%',
  },
  socialMediaIcon: {
    width: 40,
    height: 40,
    marginHorizontal: 10,
  },
});
